/**
 * pdfExport.js
 * Generates professionally formatted PDF reports using jsPDF + jsPDF-AutoTable.
 * Supports expense reports, income reports, and monthly summaries.
 */
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency, formatDate } from './formatters';

// ─── Shared Helpers ──────────────────────────────────────────────────────────

/**
 * Draw a branded header block on the first page.
 */
const drawHeader = (doc, title, subtitle) => {
  // Gradient-like header bar using a dark rectangle
  doc.setFillColor(99, 102, 241); // Indigo accent
  doc.rect(0, 0, 210, 32, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('SmartTracker', 14, 13);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(title, 14, 22);

  if (subtitle) {
    doc.setFontSize(9);
    doc.setTextColor(220, 220, 255);
    doc.text(subtitle, 14, 29);
  }

  // Reset text colour
  doc.setTextColor(30, 30, 30);
};

/**
 * Draw a footer with page numbers on every page.
 */
const drawFooters = (doc) => {
  const pageCount = doc.internal.getNumberOfPages();
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text(
      `Generated by SmartTracker  •  Page ${i} of ${pageCount}`,
      105,
      doc.internal.pageSize.height - 8,
      { align: 'center' }
    );
  }
};

// ─── Expense PDF ─────────────────────────────────────────────────────────────

/**
 * Export an expense list as a PDF.
 * @param {Array}  expenses  - Array of expense objects
 * @param {object} user      - { name, email }
 * @param {object} filters   - { month, year, category, startDate, endDate }
 */
export const exportExpensesPDF = (expenses, user, filters = {}) => {
  const doc = new jsPDF();

  const periodLabel = filters.month && filters.year
    ? `${new Date(filters.year, filters.month - 1).toLocaleString('default', { month: 'long' })} ${filters.year}`
    : filters.startDate && filters.endDate
      ? `${filters.startDate} to ${filters.endDate}`
      : 'All Time';

  drawHeader(doc, 'Expense Report', `Period: ${periodLabel}`);

  // Meta info block
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.text(`User: ${user?.name || 'N/A'}  |  Email: ${user?.email || 'N/A'}`, 14, 40);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`, 14, 46);
  if (filters.category) doc.text(`Category Filter: ${filters.category}`, 14, 52);

  // Calculate total
  const total = expenses.reduce((sum, e) => sum + e.amount, 0);

  // Table
  autoTable(doc, {
    startY: 58,
    head: [['#', 'Description', 'Category', 'Date', 'Notes', 'Amount']],
    body: expenses.map((e, i) => [
      i + 1,
      e.title,
      e.category,
      formatDate(e.date),
      e.description || '—',
      formatCurrency(e.amount)
    ]),
    foot: [['', '', '', '', 'Total', formatCurrency(total)]],
    headStyles: { fillColor: [99, 102, 241], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [239, 68, 68], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 249, 255] },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: { 5: { halign: 'right', fontStyle: 'bold' } },
  });

  drawFooters(doc);
  doc.save(`expense-report-${Date.now()}.pdf`);
};

// ─── Income PDF ───────────────────────────────────────────────────────────────

/**
 * Export an income list as a PDF.
 * @param {Array}  incomes   - Array of income objects
 * @param {object} user      - { name, email }
 * @param {object} filters   - { month, year, source, startDate, endDate }
 */
export const exportIncomePDF = (incomes, user, filters = {}) => {
  const doc = new jsPDF();

  const periodLabel = filters.month && filters.year
    ? `${new Date(filters.year, filters.month - 1).toLocaleString('default', { month: 'long' })} ${filters.year}`
    : filters.startDate && filters.endDate
      ? `${filters.startDate} to ${filters.endDate}`
      : 'All Time';

  drawHeader(doc, 'Income Report', `Period: ${periodLabel}`);

  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.text(`User: ${user?.name || 'N/A'}  |  Email: ${user?.email || 'N/A'}`, 14, 40);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`, 14, 46);

  const total = incomes.reduce((sum, i) => sum + i.amount, 0);

  autoTable(doc, {
    startY: 58,
    head: [['#', 'Description', 'Source', 'Date', 'Notes', 'Amount']],
    body: incomes.map((inc, i) => [
      i + 1,
      inc.title,
      inc.source,
      formatDate(inc.date),
      inc.description || '—',
      formatCurrency(inc.amount)
    ]),
    foot: [['', '', '', '', 'Total', formatCurrency(total)]],
    headStyles: { fillColor: [16, 185, 129], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [16, 185, 129], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [240, 253, 244] },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: { 5: { halign: 'right', fontStyle: 'bold' } },
  });

  drawFooters(doc);
  doc.save(`income-report-${Date.now()}.pdf`);
};

// ─── Monthly Summary PDF ──────────────────────────────────────────────────────

/**
 * Export a combined monthly summary (income + expenses + balance).
 * @param {object} summary   - { totalIncome, totalExpenses, balance, recentTransactions }
 * @param {Array}  monthly   - Monthly trend array [{ name, Income, Expenses }]
 * @param {object} user      - { name, email }
 * @param {number} month
 * @param {number} year
 */
export const exportMonthlySummaryPDF = (summary, monthly, user, month, year) => {
  const doc = new jsPDF();
  const monthName = new Date(year, month - 1).toLocaleString('default', { month: 'long' });

  drawHeader(doc, 'Monthly Financial Summary', `${monthName} ${year}`);

  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.text(`User: ${user?.name || 'N/A'}  |  Email: ${user?.email || 'N/A'}`, 14, 40);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`, 14, 46);

  // KPI summary table
  autoTable(doc, {
    startY: 54,
    head: [['Metric', 'Amount']],
    body: [
      ['Total Income', formatCurrency(summary?.totalIncome || 0)],
      ['Total Expenses', formatCurrency(summary?.totalExpenses || 0)],
      ['Net Balance', formatCurrency(summary?.balance || 0)],
    ],
    headStyles: { fillColor: [99, 102, 241], textColor: 255 },
    bodyStyles: { fontSize: 11 },
    columnStyles: { 1: { halign: 'right', fontStyle: 'bold' } },
    styles: { cellPadding: 5 },
  });

  // Monthly trends table
  if (monthly && monthly.length > 0) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 30, 30);
    doc.text('Monthly Trends', 14, doc.lastAutoTable.finalY + 14);

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 18,
      head: [['Period', 'Income', 'Expenses', 'Net']],
      body: monthly.map(m => [
        m.name,
        formatCurrency(m.Income || 0),
        formatCurrency(m.Expenses || 0),
        formatCurrency((m.Income || 0) - (m.Expenses || 0))
      ]),
      headStyles: { fillColor: [99, 102, 241], textColor: 255 },
      alternateRowStyles: { fillColor: [248, 249, 255] },
      columnStyles: {
        1: { halign: 'right' },
        2: { halign: 'right' },
        3: { halign: 'right', fontStyle: 'bold' }
      },
      styles: { fontSize: 9, cellPadding: 4 },
    });
  }

  drawFooters(doc);
  doc.save(`monthly-summary-${monthName}-${year}.pdf`);
};
